"options":
  "port":
    "type": "int"
    "default": !!int "9128"
    "description": "Prometheus ceph_exporter listening port (default 9128)"
  "install_sources":
    "default": ""
    "type": "string"
    "description": |
      YAML list of additional installation sources, as a string. The number of
      install_sources must match the number of install_keys. For example:
        install_sources: |
         - ppa:project1/ppa
         - ppa:project2/ppa
  "install_keys":
    "default": ""
    "type": "string"
    "description": "YAML list of GPG keys for installation sources, as a string. For\
      \ apt repository\nURLs, use the public key ID used to verify package signatures.\
      \ For \nother sources such as PPA, use empty string. This list must have the\
      \ \nsame number of elements as install_sources, even if the key items are \n\
      all empty string. An example to go with the above for install_sources:\n  install_keys:\
      \ |\n   - \"ABC\"\n   - \"\"\n"
  "ceph.config":
    "default": ""
    "type": "string"
    "description": |
      path to ceph config file (default /etc/ceph/ceph.conf)
  "ceph.user":
    "default": ""
    "type": "string"
    "description": |
      Ceph user to connect to cluster. (default "admin")
  "exporter.config":
    "default": ""
    "type": "string"
    "description": |
      Path to ceph exporter config. (default "/etc/ceph/exporter.yml")
  "telemetry.addr":
    "default": ""
    "type": "string"
    "description": |
      host part of exporter telemetry.addr, port is set via port option (no default)
  "telemetry.path": 
    "default": ""
    "type": "string"
    "description": |
      URL path for surfacing collected metrics (default "/metrics")
